#!/bin/bash
# Installer.sh - Cool Kids Craft - Aeronautics - Installer for macOS and Linux

REPO_URL="https://github.com/Faryzal2020/CoolKidsCraft-Aeronautics.git"
INSTANCE_NAME="Cool Kids Craft - Aeronautics"

echo "=============================================="
echo "   Cool Kids Craft - Aeronautics Installer"
echo "=============================================="

# 1. Detect OS and set paths
if [[ "$OSTYPE" == "darwin"* ]]; then
    PLATFORM="macOS"
    PRISM_DATA="$HOME/Library/Application Support/PrismLauncher"
    PRISM_EXE="/Applications/Prism Launcher.app/Contents/MacOS/prismlauncher"
    DESKTOP="$HOME/Desktop"
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    PLATFORM="Linux"
    DESKTOP="$HOME/Desktop"
    # Check for Flatpak
    if [ -d "$HOME/.var/app/org.prismlauncher.PrismLauncher" ]; then
        PRISM_DATA="$HOME/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher"
        PRISM_EXE="flatpak run org.prismlauncher.PrismLauncher"
    else
        PRISM_DATA="$HOME/.local/share/PrismLauncher"
        PRISM_EXE="prismlauncher"
    fi
else
    echo "[-] Unsupported Operating System: $OSTYPE"
    exit 1
fi

echo "[+] Detected Platform: $PLATFORM"

# 2. Check for Prism Launcher
if [ ! -d "$PRISM_DATA" ]; then
    echo "[-] Prism Launcher data not found at $PRISM_DATA"
    echo "Please install Prism Launcher first: https://prismlauncher.org/"
    exit 1
fi

# 3. Check for Git
if ! command -v git &> /dev/null; then
    echo "[-] Git is not installed. Please install git first."
    exit 1
fi
echo "[+] Git is ready."

# 4. Clone Repository
TARGET_DIR="$PRISM_DATA/instances/$INSTANCE_NAME"
if [ ! -d "$TARGET_DIR" ]; then
    echo "[*] Cloning modpack repository..."
    git clone "$REPO_URL" "$TARGET_DIR"
    if [ $? -ne 0 ]; then
        echo "[-] Failed to clone repository."
        exit 1
    fi
else
    echo "[*] Modpack folder already exists. Skipping clone."
fi

# 5. Create Launcher Script
LAUNCHER_PATH="$TARGET_DIR/Launch-Aeronautics.sh"
echo "[*] Creating launcher script..."
cat <<EOF > "$LAUNCHER_PATH"
#!/bin/bash
# Launch-Aeronautics.sh
cd "\$(dirname "\$0")"
echo "--- Checking for Modpack Updates ---"
git fetch --all
git reset --hard origin/main
echo "--- Launching Prism Launcher ---"
$PRISM_EXE --launch "$INSTANCE_NAME"
EOF
chmod +x "$LAUNCHER_PATH"

# 6. Create Desktop Shortcut
if [ "$PLATFORM" == "macOS" ]; then
    SHORTCUT="$DESKTOP/$INSTANCE_NAME.command"
    echo "[*] Creating macOS Desktop shortcut (.command)..."
    cat <<EOF > "$SHORTCUT"
#!/bin/bash
# This file is automatically generated by the Modpack Installer
"$LAUNCHER_PATH"
EOF
    chmod +x "$SHORTCUT"
    echo "[+] Shortcut created: $SHORTCUT"
elif [ "$PLATFORM" == "Linux" ]; then
    SHORTCUT="$DESKTOP/CoolKidsCraft.desktop"
    echo "[*] Creating Linux Desktop shortcut (.desktop)..."
    cat <<EOF > "$SHORTCUT"
[Desktop Entry]
Name=$INSTANCE_NAME
Comment=Launch $INSTANCE_NAME with Auto-Updates
Exec="$LAUNCHER_PATH"
Icon=prismlauncher
Terminal=true
Type=Application
Categories=Game;
EOF
    chmod +x "$SHORTCUT"
    echo "[+] Shortcut created: $SHORTCUT"
fi

echo "=============================================="
echo "   Installation Complete! Have fun!"
echo "=============================================="
