#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Apr 26 21:38:15 WIB 2026
allowUnknownShaders=true
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=
