#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Apr 25 19:05:50 WIB 2026
allowUnknownShaders=true
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=
